schemaVersion: "2.2"
description: Docker Deployment
parameters:
  image:
    type: String
  name:
    type: String
  ports:
    type: String
    default: ""
  env:
    type: String
    default: ""
  cmd:
    type: String
    default: ""
mainSteps:
  - action: aws:runShellScript
    name: checkDockerInstallation
    inputs:
      runCommand:
        - |
          MAX_RETRIES=5
          RETRY_COUNT=0
          while [[ $(systemctl is-active docker) != "active" ]]; do
            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
              echo "Docker is not active after $MAX_RETRIES retries. Exiting."
              exit 1
            fi
            echo "Docker is not active. Retry #$((++RETRY_COUNT))..."
            sleep 10
          done
          docker --version
      onFailure: exit
  - action: aws:runShellScript
    name: rolloutApplication
    inputs:
      runCommand:
        - |
          ${login_command}
          docker rm -f {{name}} 2>/dev/null || true
          docker image prune -a --force
          docker image pull {{image}}:latest
          docker run --restart unless-stopped -d {{ports}} {{env}} --name {{name}} {{image}}:latest {{cmd}}
