schemaVersion: "2.2"
description: Docker Deployment
parameters:
  name:
    type: String
    default: "${name}"
  ports:
    type: String
    default: "${ports}"
  env:
    type: String
    default: "${env}"
  cmd:
    type: String
    default: "${cmd}"
mainSteps:
  - action: "aws:runShellScript"
    name: deployApplication
    inputs:
      runCommand:
        - |
          ${login_command}
          CURRENT_CONTAINER=$(docker ps -aql --filter ancestor=${image}:latest --format='{{.ID}}')
          if [ ! -z $CURRENT_CONTAINER ]; then docker rm -f $CURRENT_CONTAINER; fi
          sudo docker image prune -a --force
          sudo docker image pull ${image}:latest
          sudo docker run --restart unless-stopped -d {{ports}} {{env}} --name {{name}} ${image}:latest {{cmd}}
