schemaVersion: "2.2"
description: Docker Deployment
parameters:
  name:
    type: String
    default: "${name}"
  ports:
    type: String
    default: "${ports}"
  env:
    type: String
    default: "${env}"
  cmd:
    type: String
    default: "${cmd}"
mainSteps:
  - action: aws:runShellScript
    name: checkDockerInstallation
    inputs:
      runCommand:
        - |
          MAX_RETRIES=5
          RETRY_COUNT=0
          while [[ $(systemctl is-active docker) != "active" ]]; do
            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
              echo "Docker is not active after $MAX_RETRIES retries. Exiting."
              exit 1
            fi
            echo "Docker is not active. Retry #$((++RETRY_COUNT))..."
            sleep 10
          done
          docker --version
      onFailure: exit
  - action: aws:runShellScript
    name: rolloutApplication
    inputs:
      runCommand:
        - |
          ${login_command}
          CURRENT_CONTAINER=$(docker ps -al --filter ancestor=${image}:latest --format='{{.ID}}')
          if [ ! -z $CURRENT_CONTAINER ]; then docker rm -f $CURRENT_CONTAINER; fi
          docker image prune -a --force
          docker image pull ${image}:latest
          docker run --restart unless-stopped -d {{ports}} {{env}} --name {{name}} ${image}:latest {{cmd}}
